version: '3.9'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
